### ISSUE TITLE
`pod try WistiaKit` don't build good

### ISSUE THREAD

**Issue by spinosa** [wistia/WistiaKit#16]
The `@testable import WistiaKit` is failing b/c WK isn't built with testability, apparently.  

It is built properly when you clone the repo.  Need to figure out what's changing when you `pod try`

See *Build Settings | Enable Testability*

/cc @mrdavidjcole @jordanmunson

**Comment by spinosa** [comment]
Seems like this is a classic *Derived Data* problem...

@mrdavidjcole can you please try the following, and let me know if it fixes your issue:

1.  `pod try WistiaKit` and wait for it to open Xcode (version 7.3.x)
2.  Select *Window | Projects* to bring up the Projects organizer
    - On the left, **WistiaKit Open** should be selected
3. Find the *Derived Data* row in the middle and click **Delete..**
    - Project should start rebuilding, this time successfully
4. Back in the main Xcode window, try *Product | Test*

Let me know if that works.  *IF IT DIDN'T* please try these additional steps:

1.  Close Xcode
2.  `rm -rf` the directory that `pod try WistiaKit` installed to
3.  `pod try WistiaKit`
4.  Repeat the *Derived Data* deletion steps from above

**Comment by mrdavidjcole** [comment]
@spinosa that first set of steps fixed the issue. No need to go with the nuclear option. Thanks!
