### ISSUE TITLE
Video not showing in WistiaPlayer

### ISSUE THREAD

**Issue by JaleelNazir** [wistia/WistiaKit#19]
I am trying to integrate WistiaPlayer with our App for the onBoarding videos. The problem which we are facing is, the video in UIView doesn't show-up but the audio is there. I am only able to hear audio. Below is the snippet from the code-base, can anyone guide me what possibly is going wrong;
```
    override func viewDidLoad() {
        super.viewDidLoad()

        self.view.setNeedsLayout()
        self.view.layoutIfNeeded()

        wistiaPlayer.delegate = self
        wistiaPlayer.replaceCurrentVideoWithVideoForHashedID("id")

        videoPlayer.layer.addSublayer(wistiaPlayer.newPlayerLayer()!)
        videoPlayer.clipsToBounds = true
        videoPlayer.layer.masksToBounds = true
    }
```

**Comment by spinosa** [comment]
@JaleelNazir are you sure the view and playerLayer are positioned such that you can see them?

`AVPlayerLayer` (which is vended by `WistiaPlayer.newPlayerLayer()`) has initial size of `CGRectZero`. 

Try updating your `viewDidLoad` to this:
```
    override func viewDidLoad() {
        wistiaPlayer.delegate = self
        if let playerLayer = wistiaPlayer.newPlayerLayer() {
                playerLayer.frame = videoPlayer.layer.bounds
                videoPlayer.layer.addSublayer(playerLayer)
        }
        wistiaPlayer.replaceCurrentVideoWithVideoForHashedID("id")
    }
```

Positioning won't be perfect, but you should see your video content.

PS: I'll update the README to make this clear

**Comment by JaleelNazir** [comment]
@spinosa Thanks. Its working now...
