### ISSUE TITLE
assets missing resolutions / PaintCode

### ISSUE THREAD

**Issue by hixfield** [wistia/WistiaKit#21]
Looking at the Pod/Assets/WistiaKitAssetCatalog.xcassets I see that:
- @3 is missing skullNBones
- @2 en @3 is missing for closedCaptions

I have been using PaintCode to avoid using images for over 2 years now to high effect, it would maybe be a good idea to do the same. If you have the icons in SVG you can import them in PaintCode generate a stylkit...

**Comment by spinosa** [comment]
Thanks for pointing that out.  Will add the missing assets.
