### ISSUE TITLE
video played immediately via segue in prepareForSegue leaves play button

### ISSUE THREAD

**Issue by hixfield** [wistia/WistiaKit#22]
I have my own VC with a segue to a WistiaPlayerViewController, I use performSegue to start playing (gives me some advantages when moving to iPad). 

![screen shot 2016-09-05 at 09 05 17](https://cloud.githubusercontent.com/assets/9302613/18239804/e3887256-7347-11e6-844b-5ee1fa1451d2.png)

However I want the video to play straight away
it does play immediately using the below code. However the big playbuton > stays on the screen.

    
![simulator screen shot 05 sep 2016 09 02 16](https://cloud.githubusercontent.com/assets/9302613/18239730/7e6d060c-7347-11e6-81a6-f264acfd6a2a.png)

```
override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if let
            vc = segue.destinationViewControllerPossiblyAfterNavigationController as? WistiaPlayerViewController,
            video = sender as? Video {
            vc.replaceCurrentVideoWithVideoForHashedID(video.wistiaHashId)
            vc.play()
        }
    }
```

**Comment by spinosa** [comment]
thanks, will debug this week

**Comment by spinosa** [comment]
@hixfield This is fixed on the swift_3 branch.  I will be merging that to master soon (now that we have Xcode GM).
