### ISSUE TITLE
playing video autorotation?

### ISSUE THREAD

**Issue by hixfield** [wistia/WistiaKit#23]
My app only support portrait mode except...
Previously when I was using the standard AVPlayerViewController the video played full screen
and in landscape (if device was rotated), which is what I need.

Now when using WistiaPlayerViewController the player is locked in portrait mode.

I use this code to play:

    func playVideo(hashedID: String) {
        let wistiaPlayerVC = WistiaPlayerViewController(referrer: "", requireHLS: true)
        wistiaPlayerVC.replaceCurrentVideoWithVideoForHashedID(hashedID)
        self.presentViewController(wistiaPlayerVC, animated: true, completion: nil)
    }

**Comment by hixfield** [comment]
I fixed this by :
1. Configuration my app to support all interface orientations (configure via your target in xCode)
2. In my viewControllers, tabbar vc, ... limiting their device orientations using 

    override func supportedInterfaceOrientations() -> UIInterfaceOrientationMask {
        return .Portrait
    }
    
    override func shouldAutorotate() -> Bool {
        return true
    } 
3. Then the "default" orientations apply to the WistiaPlayerViewController which is then all orientations.

This does not behave the same way as the AVPlayerViewController, which seams to always support orientation. So it might still be a good idea to look into this if you strive for max compatibility with AVPlayerViewController

**Comment by spinosa** [comment]
It's surprising to me to hear `AVPlayerViewController` doesn't respect the supported orientation of the app and/or view controller hierarchy.

I think your solution is more clear than having a VC live "outside" the normal orientation paradigm.
