### ISSUE TITLE
captions not showing

### ISSUE THREAD

**Issue by hixfield** [wistia/WistiaKit#24]
I am using the below code to play a sample video I made that contains English and Dutch captions.
1. Captions are not showing
2.How can I set the language to use for the captions? My app contains a manual language selection that is different from the iOS language...

HashId of sample video is 1m9zwtusb3 you can play by: 
https://hixfield.wistia.com/medias/1m9zwtusb3

```
    func playVideo(hashedID: String) {
        let vc = WistiaPlayerViewController(referrer: "", requireHLS: true)
        vc.replaceCurrentVideoWithVideoForHashedID(hashedID)
        presentViewController(vc, animated: true, completion: nil)
    }
```

**Comment by hixfield** [comment]
problem seams to be on HLS only if requireHLS = false, then captions are fine.
I need HLS though... :(

**Comment by spinosa** [comment]
Well, that's frustrating!
Thanks for digging in, I will debug this week.

**Comment by spinosa** [comment]
# RE 1
Changing the value of `requireHLS` did not have any affect on captions in my testing.  They always worked.  

I tested captions for the video you mentioned on the swift3 branch of WistiaKit, but I wouldn't expect this bit of functionality to be broken on the master branch and working on the swift3 branch.

I did notice that the test captions end at 14s. Maybe you missed them?

# RE 2
Instructions for custom implementation can be found in the [README](https://github.com/wistia/WistiaKit#closed-captioning)
