### ISSUE TITLE
direct access to thumbnail url without API call

### ISSUE THREAD

**Issue by hixfield** [wistia/WistiaKit#26]
I have been using wistiaAPI.showMedia and the resulting media.thumbnail.url for retrieving the URL for downloading the thumbnail image. Problem is that this wistiaAPI.showMedia call takes to much time (somewhere between 2 - 12 seconds!) which makes the UI of the app to slow (thumbnails are displayed in a tableview for different videos).

I notice the returned urls all have the same format like:

https://embed-ssl.wistia.com/deliveries/ab986f28e43f03cd2d58805a89b6b4925062ffdc.jpg?image_crop_resized=200x120
https://embed-ssl.wistia.com/deliveries/013bf05eed6b89038dd2a12a13b82d5b559659fa.jpg?image_crop_resized=200x120
https://embed-ssl.wistia.com/deliveries/c2bd1513301ad3f619ab2a8142346c5232157d82.jpg?image_crop_resized=200x120
...

In order to avoid the web service call round-trip, would it be possible to construct the thumbnail url inside the app based on the wistia hash id somehow?

**Comment by spinosa** [comment]
Sorry, there is no direct access to thumbnails as you're requesting.

That being said, I've had great results in apps using the API to get full thumb URLs, then requesting those thumbs.  Even though it's an additional request, you can get multiple medias back in a single medias request.  Hopefully you're not making an API + a Thumbnail request for each image.

But 2-12 seconds for an API call is terrible.  What does a `ping https://api.wistia.com` look like from the same device+connection?

**Comment by hixfield** [comment]
I am only using the wistiaAPI.showMedia call once and are caching the results so its a one-time-call only. Problem was really the 2-12 second delay. However, I believe it must have been a temporary issue because currently the API calls are very fast and the problem has gone away. I will keep an eye on it, and if it returns do a ping test and let you know.
