### ISSUE TITLE
Add documentation for including in Obj-c project.

### ISSUE THREAD

**Issue by mmoutenot** [wistia/WistiaKit#27]
There are likely cases with older applications or implementations that do not use swift that could benefit from a small nod in the docs!

**Comment by spinosa** [comment]
@mmoutenot have you tried this?  I don't think there's any trick, just add the `pod` line like the readme says!  Swift was built to interop w/ obj-c from the get go; it uses the obj-c runtime.

**Comment by spinosa** [comment]
@bobongski , you mentioned you're using WK in an ObjC project.  Any tips here?  Thanks!

**Comment by bobongski** [comment]
Install
pod 'WistiaKit'

//View Controller
#import <WistiaKit/WistiaKit-Swift.h>

//Alloc 
WistiaPlayerViewController *vc = [[WistiaPlayerViewController alloc] initWithReferrer:@"example" requireHLS:true];
[vc  replaceCurrentVideoWithVideoForHashedID:@"videoID"];
[self presentViewController:vc animated:true completion:nil];

**Comment by spinosa** [comment]
Thanks @bobongski !
