### ISSUE TITLE
Expose seek time to WistiaPlayerViewController

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#33]
I'm working on a project where I play a video in-line, and when the user taps on it, it automatically expands into a full-size view. To accomplish this, I'm going from a `WistiaFlatPlayerView`, taking it's hashed ID, and creating a `WistiaPlayerViewController` that I present.

If the user is in the middle of watching the video, I would like to start the video at the point where they left off in-line. I noticed your internal implementation would be able to do that, but it's not exposed to the public facing API because `WistiaPlayerViewController`'s `WistiaFlatPlayerView` is internal to the framework.

Would it be possible to expose the `seek` function externally, or allow access to `WistiaPlayerViewController`'s `WistiaFlatPlayerView` for public consumption?

Thanks a lot!

**Comment by spinosa** [comment]
Hey @mergesort ,

I think the best user experience to go from inline playback to fullscreen playback would maintain the same `WistiaPlayer`.  Video would continue playing uninterrupted during the resize.  It would feel similar to playing a video inline in Safari, then tapping the fullscreen button.

What is the reason not to use `WistiaPlayerViewController` for the inline playback (and then resizing that view controller)?

**Comment by mergesort** [comment]
I didn't see any documentation or code for `WistiaPlayerViewController` supporting in-line playback, am I just missing that? That's the reason I was using a `WistiaFlatPlayerView`.

In my user experience, I have a UIView subclass for displaying the video (and a preview imageView on top, so that's why it's a subclass). When the user taps on the imageView, it starts playing, and then when the user taps on a playing video, it expands into the full screen view.

Are you suggesting I add a `WistiaPlayerViewController` to the UIView subclass to manage the video playback on the view?

Thoughts appreciated!

**Comment by mergesort** [comment]
I also see a way for `WistiaFlatPlayerView` exposes a `wistiaPlayer`, but not the same for `WistiaPlayerViewController`. I think that would solve my problem as well, though I'm not sure if that's intentional.

**Comment by spinosa** [comment]
`WistiaPlayerViewController` doesn't have any "special" inline capabilities to speak of.  It doesn't need them to accomplish what you want.  Since it just presents your content, edge to edge, and you can treat it like any other UIViewController, I would add it as a child view controller in your hierarchy.

That is, take the current `UIView` that displays the video and preview image, and instead display a `WistiaPlayerViewController` (which will also handle displaying the preview poster before playback).  Be sure to follow the container vc paradigm: https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html

**Comment by spinosa** [comment]
@mergesort hope that helped!  Please feel free to re-open this or email dspinosa@wistia.com if I can be of more help

**Comment by mergesort** [comment]
Thank you, I appreciate it. I will come back to this when I get a chance. I currently am getting around the problem in the app I'm building, but don't think that the solution actually quite captures what I need, but that's my fault for not explaining it well enough yet. I'll throw a sample project up when I'm back to working on it, to make it more clear.

Thank you again for the help!
