### ISSUE TITLE
Expose WistiaPlayer from WistiaPlayerViewController

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#34]
I wanted to expand upon an idea I broached in #33.

There are a few things I've wanted to do using a `WistiaPlayerViewController` which would work in `AVPlayerViewController`, which are not possible in WistiaKit currently.

One thing `AVPlayerViewController` allows you to do is change the playback `rate` via `AVPlayerViewController`'s `.player` property, which is something I would like to be able to do as well. Another as mentioned before is to change it's `seek` time.

The more I'm using WistiaKit, the more of these situations I run across, like trying to get the `currentTime`, the more I think that the right solution rather than exposing some of these via a shim is to just expose the `.player` property on `WistiaPlayerViewController`.

I look forward to hearing your thoughts and feedback.

Thanks!

**Comment by spinosa** [comment]
The underlying `AVPlayer` is kept private to make sure certain Wistia things work as expected (statistics and 360 video support come to mind).

It doesn't seem too dangerous to expose the `WistiaPlayer` via `WistiaPlayerViewController.wPlayer` which would give you the ability to `.seek(...)`, query `.currentTime()`, and get/set `.rate`.

How does that feel?

**Comment by mergesort** [comment]
That sounds great. IT's actually what I was attempting to suggest, sorry if that wasn't clear. 🙂

**Comment by bschwartz** [comment]
@spinosa To what extent can we align all those methods so they match the ones from our JavaScript player? https://wistia.com/doc/player-api#methods

Or perhaps we have a shim where we add these methods over time while still giving folks access to the underlying player object in case we're slow about adding stuff and they really want low level control?

**Comment by spinosa** [comment]
@mergesort 👍 I'm on it :-]

@bschwartz 
The shim is already in place and it's what I will be exposing; `WistiaPlayer`.

The methods being discussed in this thread -- implemented on `WistiaPlayer` -- are essentially standards on iOS; they are defined on Apple's `AVPlayer`.  To make WK easy to learn and use, I've tried to keep parity with iOS frameworks where it makes sense.

Are there any particular methods of the JS API you'd like to see better alignment with?  For example, WK uses `rate` where the JS API uses `playbackRate`.  The former will be more familiar to experienced iOS devs, but insofar as WK encourages folks to jump into iOS anew, the later may be a better option.  Maybe documentation can help (ie. mention playbackRate in the iOS headers to help with grepping the docs)?

**Comment by bschwartz** [comment]
@spinosa Gotcha. Don't have a super strong opinion here. Erring on the side of keeping things iOS-like where there's an analog makes sense to me though, even if it means divergence from the JS API.

**Comment by mergesort** [comment]
If I could have a vote, I would also say stick with mimic'ing the native API's, so it's easier to reason about as an iOS developer. And if not, I didn't say anything. 🙊

**Comment by bschwartz** [comment]
@mergesort Haha, looks like we commented at the same time. And looks like we all agree here!
