### ISSUE TITLE
How can I get referrer on my wistia account?

### ISSUE THREAD

**Issue by bobongski** [wistia/WistiaKit#37]
Is there a way to jump to specific seconds on WistiaPlayerViewController??

**Comment by spinosa** [comment]
Hi @bobongski!

Choosing `referer` is up to you; it's not a property of your Wistia account.  However, if you are using playback domain restrictions, the `referer` used in WistiaKit needs to be compatible with those restrictions.

Seeking is exposed on the underlying `WistiaPlayer` that provides playback for your `WistiaPlayerViewController`.  You can seek on that by using something like: `wistiaPlayerViewController.wPlayer.seek(to:withTolerance:completionHandler:)`

**Comment by spinosa** [comment]
Looks like we're all good here?

If not, please reopen or create a new issue.  Happy to help!
