### ISSUE TITLE
How to properly dealloc WistiaPlayerViewController?

### ISSUE THREAD

**Issue by bobongski** [wistia/WistiaKit#38]
The wistiakit is great.
Is there a proper way to dealloc  WistiaPlayerViewController?
It stock on my memory even thought I put it on nil. 
I am currently using obj-c.

Thanks more power.

**Comment by spinosa** [comment]
Hey @bobongski , I've found a reference cycle preventing the `WistiaPlayerViewController` from dealloc'ing even if you nil out your references to it.

Going to inspect a bit deeper then push a fix, hopefully later today.

Good find, thanks!

**Comment by spinosa** [comment]
Fixed by 53d12e6

Will be included in next pod update (likely 0.20.2)
