### ISSUE TITLE
Layout crash

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#39]
We're gotten about a dozen of these crash reports coming from `WistiaPlayerViewController` in our app, across just a few hundred users.

The crash is occurring in this call, across devices, OS's, screen sizes, etc.
```
WistiaPlayerViewController.present(forProgress : Float, currentTime : CMTime?) -> ()
```

Specifically:
```
NSInternalInconsistencyException
Application threw exception NSInternalInconsistencyException: NSLayoutConstraint constant is not finite!  That's illegal.  constant:nan firstAnchor:<NSLayoutDimension:0x172c68380 "UIView:0x14598cec0.width"> secondAnchor:(null)
```

Let me know if there's any more information I can provide you with. Thanks!

**Comment by spinosa** [comment]
@mergesort Great report, exactly what I needed, thanks!

I wasn't able to repro, but it's clear that `progress` is NaN in that call.

I patched with a `guard` that will prevent crashes in production, but will stop at the `assertionFailure` in development.  If you catch this, I would appreciate a stack trace to help me understand how the unexpected input is getting generated.

**Comment by mergesort** [comment]
Thanks for patching this up!

I haven't been able to see it in personally, and for some reason Sentry doesn't seem to provide proper stack traces as best I can tell.
