### ISSUE TITLE
Crashing when still loading then rotating the wistiaviewcontroller

### ISSUE THREAD

**Issue by bobongski** [wistia/WistiaKit#42]
Hi man,

The app crash here: 
internal func present(forProgress progress: Float, currentTime: CMTime?){
        guard progress.isFinite else {
            assertionFailure("progress expected to be finite")
            return
        }

When I try to rotate the device while it is still loading.
Great job by the way

-marlon

**Comment by spinosa** [comment]
@bobongski I assume the assertion is firing, causing the crash.

Can you provide a stack trace?

PS: In production builds, this will not crash.  It will gracefully return and the UI will be updated later.

**Comment by spinosa** [comment]
If this is still occuring, please re-open and update me!
