### ISSUE TITLE
Domain restrictions & HLS playback don't mix: 'requested media could not be found'

### ISSUE THREAD

**Issue by mrdavidjcole** [wistia/WistiaKit#47]
When embedding a video from an account with [Domain Restrictions](https://wistia.com/doc/account-setup#domain_restrictions) enabled, the video should be able to play if the `referrer` is set to a whitelisted domain, as described at https://github.com/wistia/wistiakit#initializing-wistiaplayerviewcontroller-or-wistiaplayer.

This does not currently work for HLS videos though (which is most videos), since (per @spinosa) WistiaKit does not add the referrer when requesting [the `m3u8` manifest file](https://github.com/wistia/WistiaKit/blob/master/Pod/Classes/public/model/WistiaMedia.swift#L88).

**Comment by mrdavidjcole** [comment]
@spinosa shoots HE SCORES! 🎉

**Comment by jayholman** [comment]
@spinosa I'm not sure if it's the exact same problem as occurred here, but we've been seeing the same problem where Domain Restrictions are blocking playback. A message about video not found just comes up with the skull and crossbones.

I've been using the super basic `pod try WistiaKit` example to test without other factors. Have tested across a few accounts with the same results at this point.

**Comment by spinosa** [comment]
@jayholman are you setting the `referrer` to a whitelisted domain when initializing a player?

**Comment by jayholman** [comment]
@spinosa i believe so, here's an example of what i was setting:
```
    let wistiaPlayerVC = WistiaPlayerViewController(referrer: "jayholman.xyz", requireHLS: false)

    //MARK: - WistiaPlayer Specific

    let wistiaPlayer = WistiaPlayer(referrer: "jayholman.xyz", requireHLS: false)
    @IBOutlet weak var playerView: WistiaFlatPlayerView!
```

**Comment by spinosa** [comment]
Two initial thoughts...
1) Does referrer care about http(s)?  I would try `http://jayholman.xyz"
2) The `pod try` sets up an example app where the player is initialized from Storyboard.   Unless you're replacing that player, or setting the referrer on it later, that could be the issue

**Comment by jayholman** [comment]
Great call @spinosa. It appears that referrer does care about http(s). Adjusting referrer to `http://jayholman.xyz` solved the problem. cc @gbuilds
