### ISSUE TITLE
Offline playback

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#49]
In the project I am working on, I have similar needs as were described in #46, but wanted to open discussion about full offline playback.

My plan was to save files to disk that we get from Wistia (via the API if necessary), and play them back, but I don't see any way to do that via WistiaKit, and would have to rebuild it via `AVPlayer`.

If this is something you're willing to consider, there are two ways that I think would be reasonable techniques that would be reasonable, and of course other possibilities I haven't considered.

1) Add a parameter that allows storing a video offline, and then allowing playback via an identifier, with offline.

This would look something like this:
```swift
let wistiaPlayerViewController = WistiaPlayerViewController()
wistiaPlayerViewController.replaceCurrentVideoWithVideo(forHashedID: "lalaland", cached: true)
```

2) Allow playback to be transparently determined, read off the disk if it's available, similar to the solution that @hardythedrummer suggested, with some sort of way to provide knowledge whether the file is available offline.

This would look something like this:
```swift
let wistiaPlayerViewController = WistiaPlayerViewController()
if wistiaPlayerViewController.isAvailableOffline(forHashedID: "lalaland") {
    wistiaPlayerViewController.replaceCurrentVideoWithVideo(forHashedID: "lalaland")
}
```

3) Allow playback from any offline file, by exposing WisitaKit internals, passing the video through to the `AVPlayerViewController` subsystem that WistiaKit hides.

This would look something like this:
```swift
let wistiaPlayerViewController = WistiaPlayerViewController(fileUrl: "file://myCoolFile.mp4")
```

Personally I favor solution 2, since it mimics Apple's file APIs, and is more explicit in telling us whether offline playback is supported. I'd love to hear what you think about this, and if this is something that can be built into WistiaKit.

Thanks a lot!

**Comment by need2edit** [comment]
@mergesort big 👍🏼👍🏼 on this request. 

We prefer #2 for the same reasons. 

Have you done any work with HLS persistence in AVFoundation?
https://developer.apple.com/library/content/samplecode/HLSCatalog/Introduction/Intro.html

I've made a beta version of our current app using this approach and it works really well. Our issue has been that the HLS playlist generated by the Wistia Data API doesn't provide (that I could find) the captioning information as part of the .m3u8 tracks so it is an incomplete HLS experience for us right now.

We'd love to use WistiaKit (and we have a version stubbed and ready to go), but the offline need with captioning is so important to our customers that we're sticking with our own custom approach for now... no WistiaKit in production yet 😔.

For reference, Apple's advanced streams include multiple audio, language, and captioning tracks etc. https://developer.apple.com/streaming/examples/

**Comment by spinosa** [comment]
I also prefer option 2; a simple offline API in WK to abstract the underlying implementation details of Apple's HSL persistence.

@need2edit Regarding the captioning: I will see about getting the manifest updated to include captions; it should.  What player are you using?  FWIW, the `WistiaPlayerViewController` pulls captions from the API no matter how the video is delivered.  There is a route to offline playback with caption support even w/o inclusion in the manifest.

**Comment by mergesort** [comment]
Since it seems we're all agreed on a potential solution, what are the next steps necessary to push this forward? 

Would that come by on Wistia's side, or through your work @need2edit, or something I should start looking into on my own?

**Comment by spinosa** [comment]
At the moment, offline playback is on Wistia's list, just not at the top :-]  Not because we don't think it would be great to have, there's just other stuff going on.

That being said, I would gladly make time to provide guidance and advice (from start to finish) if somebody forked WistiaKit to create an offline playback PR.

**Comment by hardythedrummer** [comment]
@mergesort im curious if there's been any movement on this - if you have a fork, I'd be happy to jump in and contribute.

**Comment by mergesort** [comment]
I have not moved forward, as it's been a bit de-prioritized for us. I'm going to build on top of AVPlayerViewController for now for offline support in our app.

**Comment by hardythedrummer** [comment]
Just made a PR to at somewhat address this: #55 
The HLS persistence mentioned earlier is unfortunately not supported on TvOS, which is the platform I'm targeting, so I opted for a solution that allows the client to implement caching in whatever way makes sense for the particular implementation.

**Comment by spinosa** [comment]
Closing this since #55 has been merged.

Offline playback via HLS Persistence has been noted as a spec for WistiaKit2.
