### ISSUE TITLE
Swift 3.1 warnings

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#50]
Would it be annoying to ask for a pod update to address #48? Warnings and what not. 😅

**Comment by spinosa** [comment]
Pushed 0.21.1!

**Comment by spinosa** [comment]
PS: I'm experimenting with splitting WistiaKit into a data portion and a presentation/playback portion.  This allows the data-only half of WK (`WistiaKitData`) to work in extensions where certain API isn't available.

Would love if you had time to check it out.  It's on the branch `djs/subspecs`.  It should work out of the box; including `pod WistiaKit` will also include the data-only `pod WistiaKitData`.

**Comment by mergesort** [comment]
Hey @spinosa. Thanks for merging!

I'm wondering what the use case is for using the data portion of WistiaKit on it's own, do have it be made into it's own subspec? I would imagine a case where I'd want the player on it's own, without a dependency on `WistiaKitData`, but wondering about the alternative case.

Thanks!

**Comment by spinosa** [comment]
The use case in our app is a share extension.  I moved bunch of common functionality into a shared framework.  To use a framework (or any code for that matter) in a share extension, there are some unavailable APIs it needs to avoid.  So the shared framework only relies on WistiaKitData

I can't think of a good way to offer playback without WistiaKitData.  Basic data models, manipulation, and wistia API access all lives in WKData.

**Comment by mergesort** [comment]
Gotcha, that totally makes sense as a use case. `WistiaKitData` evoked the idea of all the tracking info that Wistia offers, and hence thought the UI could function without it, I think `WistiaKitCore` is more what I would expect a module that includes all the APIs, data models, and manipulation to live.

One potential hierarchy I'd consider would be:
WistiaKit (WistiaKitAPI, WistiaKitCore dependencies)
-- WistiaKitAPI (API access, with WistiaKitCore as a dependency)
---- WistiaKitCore  (Models, manipulation)

That said, whatever you choose to do is alright by me, I'm just another stranger on the internet. 🙂
