### ISSUE TITLE
Removing dependency to Alamofire

### ISSUE THREAD

**Issue by MrAlek** [wistia/WistiaKit#52]
Alamofire is a huge networking library and a very big dependency to pull into this relatively small SDK. It is currently used to send two simple GET and one POST request.

This can be done with `URLSession` without having to pull in a big dependency, making the overall footprint of the SDK much smaller.

**Comment by MrAlek** [comment]
The Alamofire dependency is also somewhat blocking https://github.com/wistia/WistiaKit/issues/43 since it is complicated to do a setup with dependencies working with both CocoaPods and Carthage.

**Comment by spinosa** [comment]
👍 totally agree

Now about that time machine... ;-]

**Comment by MrAlek** [comment]
@spinosa Do you think you might work on this soonish or should I start on a PR? We're about to replace Youtube with Wistia but this issue is big enough for me to hold back on integrating WistiaKit into our app at the moment.

**Comment by spinosa** [comment]
Unfortunately @MrAlek, I won't be able to get on this very soon.

IMHO, this may be a bigger undertaking than it seems at first glance.  I know there are many reasons to keep external dependencies down, but FWIW, AlamoFire weighs in under 0.5 MB.

That being said, if you want to dive in, I'm happy to review and help get a PR merged!

**Comment by MrAlek** [comment]
@spinosa In the short term, that would work for us. We already have Alamofire as a dependency through Carthage which is why I am hesitant to pull another copy in through CocoaPods, in fear of conflicts.

**Comment by spinosa** [comment]
I have little Carthage experience but that does seem like a good route.  And maybe a little Swift PM while we're at it =)

**Comment by MrAlek** [comment]
iOS doesn't support Swift PM packages yet though, but Carthage would be great :)

**Comment by spinosa** [comment]
Carthage support has been added.  Closing this.

Noted the removal of AlamoFire as a spec for WistiaKit2.
