### ISSUE TITLE
IDFA Usage

### ISSUE THREAD

**Issue by emil622** [wistia/WistiaKit#53]
Why is IDFA used and not stated anywhere that it is used and why?...
I had the surprise at the app submission to see that the app is using the IDFA after integrating the sdk. None of the provided options seem to be appropriate to select at submission...how should we go around this?

**Comment by spinosa** [comment]
Hi @emil622 , the IDFA is used to assist with statistics on the Wistia backend.  We use WistiaKit in the Wistia Mobile App and at submission, when asked we choose `attribute this app installation to a previously served advertisement` and `attribute an action taken to a previously served advertisement`.

Is this okay for your app?

**Comment by emil622** [comment]
That will do it, thanks.
