### ISSUE TITLE
Airplay Support

### ISSUE THREAD

**Issue by sfkaos** [wistia/WistiaKit#54]
Since the WistiaPlayer is backed by AVPlayer, it should support Airplay by default. However, the WistiaPlayer hides the underlying AVPlayer and thus the AirPlay API. 

Am I looking at this correctly? Or is there another way to get access to AirPlay and get Wistia videos on Airplay devices?

**Comment by spinosa** [comment]
We've added Now Playing support on the [djs/subspecs](https://github.com/wistia/WistiaKit/tree/djs/subspecs) branch, which allows AirPlay to be selected from the NowPlaying.

Or are you looking to add a button in the player view itself?

**Comment by sfkaos** [comment]
@spinosa Thanks for replying so quickly.
 
Correct. I'm looking to add a button in the player view itself. 

I've tried this by creating an MPVolumeView and adding it to my custom player view. For context, I'm using a customized UIView (instead of the WistiaFlatPlayerView) using the AVPlayerLayer directly via the newPlayerLayer() function and adding it as a sublayer to my UIView. I did this so I have direct access to the AVPlayer so I can mute.

After adding the MPVolumeView it appeared and I tried to send the video to an AirPlay device which created a flickering of video that would crash almost immediately on the Airplay device. 

Do you have any advice?

**Comment by spinosa** [comment]
Sounds like a fine approach.  (FWIW, I am leaning toward exposing the `AVPlayer` in `WistiaPlayer`, especially since it can easily be obtained like you did - exposing it would clean things up and allow us to put some documentation in front of it)

As for the crash, I would need to know more about it.  Do you have a stack trace of the crashing thread?

**Comment by sfkaos** [comment]
Its not crashing per se, just kind of sits there. Adding the MPVolumeView should be the only code needed to support Airplay, no?

**Comment by spinosa** [comment]
The `AVPlayer` needs `allowsExternalPlayback=true` which is the default and is not changed by WistiaKit.

I've noticed AirPlay behaving oddly (including seeming to hang) if you have multiple `AVPlayer` instances ready for playback that all allow external playback.  Check to see if that may be the case.

**Comment by spinosa** [comment]
Closing this since it's stale.  AirPlay is working via control center.  Please reopen if needed
