### ISSUE TITLE
Can you help WistiaKit?

### ISSUE THREAD

**Issue by spinosa** [wistia/WistiaKit#56]
Hey there!

We're looking forward to more formally 'launching' WistiaKit later this year =)

I'm (privately) curious what you're using it for?

Additionally, we would like to (publicly) highlight some real world implementations.  Would you (or somebody you work with) be willing to chat with us about your app?  It would be great, even if we can't mention your company/app publicly yet.  But you're of course free to keep it to yourself, no worries.

Hit me up in the replies here or directly: [dspinosa@wistia.com](mailto:dspinosa@wistia.com)

Thanks!
Dan

/cc @hardythedrummer @sfkaos @MrAlek @mergesort @zocario @bobongski @emil622 @artemkrachulov @j796160836 @hixfield @JaleelNazir @need2edit @maltebaumann

**Comment by sfkaos** [comment]
Sure. Would love to chat.

**Comment by spinosa** [comment]
Cool, thanks @sfkaos @mergesort !
Look for myself or @mollywolfberg reaching out a little later this summer 🌞

**Comment by need2edit** [comment]
Would love to help! Docs, implementation any of it!

**Comment by mollywolfberg** [comment]
Thank you @sfkaos, @need2edit, and @mergesort! We'll bother you soon enough 🥇

**Comment by MrAlek** [comment]
@spinosa If this is still relevant, we'd love a chat as well about our use.

**Comment by evanspa** [comment]
Any plans for an Android port?
