### ISSUE TITLE
Wistia video customization options are not respected

### ISSUE THREAD

**Issue by acj** [wistia/WistiaKit#64]
## Steps to reproduce

1. Enable (or disable) a customization option through the Controls section of the Wistia web UI. Examples include "Autoplay", "Fullscreen", etc.
2. View the video using the WistiaKit example app

## Expected

The player respects the customization options.

## Observed

The player's appearance and behavior are the same regardless of what options are chosen.

**Comment by spinosa** [comment]
API v1 does not return embed options when a media is fetched.  

One must manually fetch via `WistiaAPI.showCustomizations(...)` then either
1) set the embed options on the media before passing it to the `WistiaPlayerViewController`
or
2) set `WistiaPlayerViewController.overridingEmbedOptions` with the options just received

Will not fix in the current Example app.  WistiaKit2 will not suffer the same problem.

/cc #62
