### ISSUE TITLE
WistiaKit videos reproducing in a loop

### ISSUE THREAD

**Issue by icefall** [wistia/WistiaKit#66]
Hello guys,

We had WistiaKit imported in our project directly. We took the source code and inserted in the project like it was ours. Now, we are moving this code to Carthage using your new Carthage support.

The problem is: we want our video reproducing in a loop. When it finishes, it starts again from the beginning. 

We were using this code that we wrote in house to do it so:
```
func didPlayToEndTime(of player: WistiaPlayer) {
    if let timeScale = player.currentItem?.asset.duration.timescale {
        let ct = CMTime(seconds: 0, preferredTimescale: timeScale)
        player.seek(to: ct, completionHandler: { (success) in
            player.play()
        })
    }
}
```

Although, this code is not working using an external module because currentItem is marked as internal.

I would like to know if we can manage to do a pull request changing this attribute to public or if there's another way to have the same effect working.

**Comment by spinosa** [comment]
Hi @icefall ,

Sorry for the delay, was on holiday!

You don't need to use the assets timescale, and so you don't need to access `currentItem`.  Just
`.seek(to: CMTime(seconds: 0, preferredTimescale: 10), ...`

timescale is essentially the denominator where seconds is the numerator.  Seeking to 0 is no problem with any non-zero timescale

PS: If a video's end behavior (as set on Wistia.com) is "loop", your desired effect should happen without any code!  Caveat: I have reason to believe that portion of WistiaKit is currently broken.  :-/  So keep doing it your way!
