### ISSUE TITLE
Airplay Support with Domain Restrictions Active

### ISSUE THREAD

**Issue by jayholman** [wistia/WistiaKit#67]
We currently been seeing an issue where playback fails when airplay is activated from a Domain Restricted account, even if it works outside or Airplay within the app.

The error is a message “An error occurred loading this content 
Try again later”

As airplay support is built out in the future, it would be ideal if we could make it possible for airplay to work with domain restrictions.

**Comment by mrdavidjcole** [comment]
@jayholman if you play a video on Airplay with domain restrictions disabled, what shows up as the referrer in the stats?

**Comment by spinosa** [comment]
This issue has been resolved.  WistiaKit + AirPlay + Domain Restrictions == 👌
