### ISSUE TITLE
Full Screen Crashes 

### ISSUE THREAD

**Issue by gwbennett** [wistia/WistiaKit#68]
When I tap on the Fullscreen button in the sample app it crashes in the FullScreenController.swift with an assert on line 24 ` assert(false, "Couldn't get ancestral views/VCs for fullscreen")`

When I implement as described in the sample app, I get the same result in my app when tapping on the full screen button. 

 I am using tag, 0.30.2. 
Any help is appreciated. 
Gary

**Comment by spinosa** [comment]
Hey @gwbennett ,

Good catch.  We missed that edge case, which is embarrassing since it's the edge case exercised by our own sample app =)

This happens because the playerViewController is already being presented modally.  It doesn't make much sense to go fullscreen when already fullscreen.  

I will be fixing this

**Comment by spinosa** [comment]
Fixed in https://github.com/wistia/WistiaKit/commit/cadcce525b7228a45a2c5b252854a238a0da5d1f

This isn't tagged or released yet, so you'll need to pull edge (not the 0.30.2 tag)

**Comment by frangulyan** [comment]
Could you please apply this to swift 4 branch also? It is a real showstopper for us now...

**Comment by spinosa** [comment]
@frangulyan commit cadcce5 is in the swift4 branch.

Please open an issue with more information about the problem you're seeing and I'm happy to dig in!

**Comment by frangulyan** [comment]
@spinosa seems like it is not there, here are the commits in swift4 branch:

https://github.com/wistia/WistiaKit/commits/djs/xcode-9

As you can see, the merge from master was done right before that fix. Both the (fix) cadcce5 and (merge) 7c4e95d have the same parent 4046f23

Am I using pods correctly?

`pod 'WistiaKitCore', :git => 'https://github.com/wistia/WistiaKit.git', :branch => 'djs/xcode-9'`
`pod 'WistiaKit', :git => 'https://github.com/wistia/WistiaKit.git', :branch => 'djs/xcode-9'`

**Comment by spinosa** [comment]
Sorry for the confusion; looks like your'e on the wrong branch.  Try the `swift4` branch, not `djs/xcode-9`

So you Podfile would look like
```ruby
pod 'WistiaKitCore', :git => 'https://github.com/wistia/WistiaKit.git', :branch => 'swift4'
pod 'WistiaKit', :git => 'https://github.com/wistia/WistiaKit.git', :branch => 'swift4'
```

**Comment by frangulyan** [comment]
Everything works fine, thanks!

It would be good to update the [README](https://github.com/wistia/WistiaKit/blob/master/README.md) file to point to the correct swift 4 branch.

**Comment by spinosa** [comment]
Absolutely @frangulyan.  Again, I'm very sorry for the confusion, and appreciate the feedback!  

See https://github.com/wistia/WistiaKit/commit/4de9d500ed98f154e4f0355f8a1bfbf48443e6d1 =)
