### ISSUE TITLE
Timeline for Swift 4 support?

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#69]
Hi there,

I was wondering what the timeline would be for a version of the SDK with Swift 4 support. I'm in the process of updating my apps for Swift 4, and this appears to be the last remaining dependency I have. I'd love to be able to move over to Swift 4 and the new build system as soon as possible.

Thanks a lot!

**Comment by spinosa** [comment]
Have a look at this branch https://github.com/wistia/WistiaKit/tree/djs/xcode-9 for Swift 4 support

I expect smooth sailing, but let me know if you hit any snags.

Plan is to get it on master in the next week

**Comment by mergesort** [comment]
@spinosa That branch appears to not be building correctly either. I'm seeing these errors when I point to that branch like so:

```ruby
pod 'WistiaKit', :git => 'https://github.com/wistia/WistiaKit.git', :branch => 'djs/xcode-9'
```

<img width="1047" alt="objc" src="https://user-images.githubusercontent.com/716513/30661387-d3ec09ca-9e11-11e7-85b4-df4014e95f09.png">
<img width="1038" alt="uuid" src="https://user-images.githubusercontent.com/716513/30661390-d5667d3a-9e11-11e7-8db5-508c39dad3fa.png">

**Comment by spinosa** [comment]
Looks like you need to `pod update WistiaKit`

ex: https://github.com/wistia/WistiaKit/blob/djs/xcode-9/Pod/Classes/Core/internal/stats/_WistiaStatsManager.swift#L207

**Comment by mergesort** [comment]
Strange, I did run that and saw (and still see) no changes.

**Comment by mergesort** [comment]
@spinosa I just tried the same thing on another project, and the same result. Maybe there's something up with configuration?

**Comment by spinosa** [comment]
I just moved our mobile app to that branch with the exact same Podfile line and `pod update WistiaKit` worked as expected.  What version of cocoapods are you using?  We're on 1.3.1

**Comment by mergesort** [comment]
Yep, 1.3.1 as well.

**Comment by mergesort** [comment]
I figured out the issue. Since it was split into `WistiaKit` and `WistiaKitCore`, I needed to add this:

```ruby
pod 'WistiaKitCore', :git => 'https://github.com/wistia/WistiaKit.git', :branch => 'djs/xcode-9'
```

On top of the original:

```ruby
pod 'WistiaKit', :git => 'https://github.com/wistia/WistiaKit.git', :branch => 'djs/xcode-9'
```

**Comment by keanufreitas** [comment]
Wow! @mergesort 's solution was mines as well. Thanks for figuring that out.
