### ISSUE TITLE
check the status before using the asset

### ISSUE THREAD

**Issue by hixfield** [wistia/WistiaKit#7]
Currently assets are being considered independent from their status.
This means that its possible that incomplete (status = 1 I believe?) or error-ed assets (status -1 I believe?) can be returned. These assets I believe can not be played (yet).
What are the enum types of the status codes?

**Comment by spinosa** [comment]
You bring up a good point @hixfield .  I will add a enum for the status codes, and in the future take this into account when trying to play a video / returning a more meaningful error.
