### ISSUE TITLE
Cannot remove close button from WistiaPlayerViewController

### ISSUE THREAD

**Issue by MrAlek** [wistia/WistiaKit#70]
Using WistiaKit 0.30.2

When embedding `WistiaPlayerViewController` there is currently (as we could find) any way to remove the "X" close button which by default closes any modal currently open.

As a workaround, we've set the delegate and no-op'ed the `close(wistiaPlayerViewController:)` function, but the button is still there even if it then does nothing.

**Comment by spinosa** [comment]
will have a look at this next week

**Comment by spinosa** [comment]
The close button only makes sense when being presented modally.  Will only show it when `WistiaPlayerViewContorller` is being presented.
