### ISSUE TITLE
Disabling full screen button with `overridingEmbedOptions` take no effect

### ISSUE THREAD

**Issue by MrAlek** [wistia/WistiaKit#72]
Using WistiaKit 0.30.2

# Steps to reproduce

1. Initialize a `WistiaPlayerViewController` with the following setup:

```
let vc = WistiaPlayerViewController(referrer: "X", requireHLS: true)
vc.overridingEmbedOptions = WistiaMediaEmbedOptions()
vc.overridingEmbedOptions?.fullscreenButton = false
```

2. Embed, add any media, show view.

# Expected

There is no full screen button in the player control bar.

# Actual

The full screen button is still there.

**Comment by spinosa** [comment]
related to #64 #62 

I will look into this confluence of Embed Options issues next week
