### ISSUE TITLE
WistiaKit crash happening

### ISSUE THREAD

**Issue by icefall** [wistia/WistiaKit#73]
Hello guys

We are experiencing this crash since the release of our last version:

http://crashes.to/s/b4628bc588a

On this version, we made from WistiaKit source inside the project to an external Carthage framework.

Can you guys help me with this? We are receiving a ton of crashes, and our users are giving low reviews on the app store.

**Comment by icefall** [comment]
@spinosa can you take a look on this?

**Comment by spinosa** [comment]
taking a look today

**Comment by spinosa** [comment]
What version of WistiaKit are you using?  I am assuming something from master, and not the `djs/xcode-9` branch.  If so, and if you're using Swift > 3.0...

The `StatsEvent` object is getting persisted with an unstable name, and subsequent attempts to load it are causing the crash.  Very sorry about this.  Growing pains with the evolving Swift language that I didn't foresee or get ahead of :-/

One solution would be to push an update with the `unarchiveObject` line commented out in `_WistiaStatsManager`.  When we get Swift 4 updates to the master branch of WK they will be robust against this particular issue.  But until then, it may be worth sacrificing some lost stats.

Please let me know if you have any other questions, or if my assumptions were wrong and the issue isn't what I explained.

**Comment by spinosa** [comment]
Latest commit should fix it for you:  7886360
It removes and ignores the old persistence file, and uses a new file with a stable archiving name.

**Comment by icefall** [comment]
The version that was released on this build was Swift 3 but we made the upgrade do Swift 4 already and we was expecting to launch this new version with Swift 4.

Do you think there's a problem to release the Swift 4 version and Wistia checked on the commit 7886360?

**Comment by spinosa** [comment]
Try building and testing with the `swift4` branch (latest commit is 209a912).  This branch has the archive fix discussed above and is fully updated for Swift 4 (unlike the master branch).

**Comment by spinosa** [comment]
Please reopen or a create a new issue if you're still having trouble!
