### ISSUE TITLE
Video Audio not working

### ISSUE THREAD

**Issue by iBAP** [wistia/WistiaKit#75]
Hi guys,

Good job by the way on this third party library.
Having trouble some device like iphone 7s it plays the video but no audio any idea about this?

**Comment by spinosa** [comment]
I am curious, if you `pod try WistiaKit` and play the same video (using it's hashedID) does this reproduce the issue?

If so, could you share the hashedID?  (If you prefer to keep it private, please email dspinosa@wistia.com )

**Comment by iBAP** [comment]
Yes I am using hashedID to play the video. Install wistiakit with pod.

**Comment by spinosa** [comment]
Is the physical mute/vibrate rocker on your phone set to mute?  If you don't have audio category set, that will mute audio.  See the readme about `AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)`

If that doesn't help...

What's the hashedID?  I would be happy to look at the specific video in question

**Comment by iBAP** [comment]
The customer said that all the video mute no matter what is the hashed ID. I will add that code to my app thanks. Here is a sample of the hashid "y36nrqsvzi".

**Comment by iBAP** [comment]
Hi spinosa.

The problem was on the ringer thing. Already added the code on the app thanks for the help.

**Comment by spinosa** [comment]
you got it!  👍
