### ISSUE TITLE
Close video button missing from WistiaPlayerViewController

### ISSUE THREAD

**Issue by odedharth** [wistia/WistiaKit#76]
I integrated the latest version of the WistiaPlayerViewController according to the documentation. 

```
func playVideo() {
wistiaPlayerVC.replaceCurrentVideoWithVideo(forHashedID: "ldm4zj8oo3")
wistiaPlayerVC.play()
self.present(wistiaPlayerVC, animated: true, completion: nil)
}

```

When I present the VC the close video button (the "X" button) is missing.
This problem occurs on all of the devices I checked (iPhone 6, iPhone X and iPad).

![img_0616](https://user-images.githubusercontent.com/624023/32457314-8b72280a-c2dd-11e7-8c2f-fb89b5c9554c.PNG)

**Comment by spinosa** [comment]
Hey, nice find, thanks for reporting!

It looks like you're seeing a timing issue here.  I was able to reproduce by delaying presentation of the ViewController.  

Just pushed a fix for this.  Please try grabbing the edge version of WistiaKit and see if this is fixed.

/cc @jayholman
