### ISSUE TITLE
Rotating the video doesn't change it to landscape

### ISSUE THREAD

**Issue by odedharth** [wistia/WistiaKit#77]
I integrated the latest version of the WistiaPlayerViewController according to the documentation.

```
func playVideo() {
wistiaPlayerVC.replaceCurrentVideoWithVideo(forHashedID: "ldm4zj8oo3")
wistiaPlayerVC.play()
self.present(wistiaPlayerVC, animated: true, completion: nil)
}
```

When I rotate the iPhone to landscape mode the video doesn't rotate accordingly.

**Comment by spinosa** [comment]
I cannot reproduce this.  Check out the example app that comes with WistiaKit; rotation works as expected.

**Comment by odedharth** [comment]
Seems that this is because the device orientation of my app is Portrait

**Comment by spinosa** [comment]
@ttakasawa are you saying the video is playing in landscape (ie. 90 degrees rotated) while your app is in portrait?

can you please share a screenshot and details on how to reproduce?

**Comment by spinosa** [comment]
Closing as stale.  Please reopen with details to repro if this is still applicable
