### ISSUE TITLE
Associating an email address with the video player stats

### ISSUE THREAD

**Issue by gbuilds** [wistia/WistiaKit#79]
This is a feature request 🎉 🎈 

It would be great to be able to pass in an email value to the WistiaKit video player, that shows up inside Wistia stats, similar to what the `email()` method on the web player;s javascript API, and the `email=` embed option do for the Wistia HTML5 player.

If this followed a similar convention as the APIs for web Wistia Player, then a) you could pass in a configuration object with values like `email=smith@wistia.com, playerColor=#1febd3` (but more Swift-like). And also b) an instance of the Player would have a method like `setEmail()`.

**Comment by spinosa** [comment]
will probably associate the email address with the `WistiaPlayer` (similar to referer)
