### ISSUE TITLE
Home button of iPhone X covers controls

### ISSUE THREAD

**Issue by moger777** [wistia/WistiaKit#82]
The home button for iPhone X covers bottom controls, specifically the track controls. This makes it hard/impossible to use track control on iPhone X in portrait mode. I think the fix for this is rather trivial, just make the bottom constraint for Overlay Container relative to it's superview margin. When I tested this with example project it moves the controls over the home button on iPhone X without changing the position for phones with physical home button. I can probably get a PR for you if you would like if you are okay with that implementation.
![screenshot 2018-01-05 10 39 20](https://user-images.githubusercontent.com/48684/34616133-304f1c10-f205-11e7-9514-8bc8190e52c0.png)

**Comment by spinosa** [comment]
That sounds like a good approach.  PR sounds good
