### ISSUE TITLE
Apple complains about advertising identifier on app submission

### ISSUE THREAD

**Issue by moger777** [wistia/WistiaKit#83]
When submitting app, I get:

Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again.

Is it possible to turn this off or provide a summary of the IDFA usage so we can submit with that?

**Comment by spinosa** [comment]
We use the IDFA to attribute the installation & actions taken within the app to previously served advertisement.  Presently, the latter two check boxes.

**Comment by moger777** [comment]
@spinosa can you let me know where checkboxes are located? Did not see them in the "Capabilities" section of the project and not sure where else they would be.

**Comment by spinosa** [comment]
I was referring to the [IDFA checkboxes during submission](https://www.google.com/imgres?imgurl=https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Art/11IDFA-Submitting_2x.png&imgrefurl=https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SubmittingTheApp.html&h=607&w=1264&tbnid=AjkYk3jkL9ZMmM:&tbnh=100&tbnw=211&usg=__o7RSmU3LfXaXxsPPZzdnTyAPvBc%3D&vet=10ahUKEwjk5K-l08jYAhXJzlMKHZNvAGQQ9QEILTAA..i&docid=X_lF5jbc6R_E3M&client=safari&sa=X&ved=0ahUKEwjk5K-l08jYAhXJzlMKHZNvAGQQ9QEILTAA)
