### ISSUE TITLE
Lag on this video hash id: mc97b035yk 

### ISSUE THREAD

**Issue by iBAP** [wistia/WistiaKit#87]
Lag on this video hash id: mc97b035yk but other video seems perfectly fine any solutions on this one?

**Comment by spinosa** [comment]
Hey @iBAP , have you reached out to support@wistia.com on this?  They are very good with issues like this.  

Unless this is WistiaKit specific..?  If so, can you please provide me with details on how to reproduce, specifically what you expected, and what happened instead?

**Comment by jayholman** [comment]
hi @iBAP, it looks like there was an encoding failure on the HLS assets for that video. I've gone ahead and kicked off a re-encode for them. If you'd like to reach out to support@wistia.com we can continue this conversation. It doesn't look like the problems in WistiaKit for this one.
