### ISSUE TITLE
Value of type '[T]' has no member 'compactMap'

### ISSUE THREAD

**Issue by ttakasawa** [wistia/WistiaKit#93]
I am currently using "WistiaKit" and "WistiaKitCore" from branch "swift4". It gives me an error saying "Value of type '[T]' has no member 'compactMap'" in _Parser.swift. 

How do I solve that?

**Comment by spinosa** [comment]
What version of Xcode and Swift are you using?  

Should compile fine in XC 9.4 with Swift 4.1

**Comment by ttakasawa** [comment]
Thanks! I was using XC 9.2
